<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="TML-MacBook-Pro.local" ignored="2" name="Normal" tests="2" failures="1" timestamp="09 Dec 2019 19:51:05 GMT" time="47.883" errors="0">
  <testcase name="loginWithInvalidCredentials" time="4.565" classname="testCases.LoginTestCases">
    <failure type="java.lang.AssertionError" message="Login failed expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: Login failed expected [false] but found [true]
at com.cloud.pageActions.LoginPage.loginInApp(LoginPage.java:46)
at testCases.LoginTestCases.loginWithInvalidCredentials(LoginTestCases.java:21)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- loginWithInvalidCredentials -->
  <testcase name="validateShortestDurationInDeutscheBahn" time="10.084" classname="testCases.TripsTesting"/>
  <testcase name="@BeforeTest initTestSuite" time="0.0" classname="testCases.BaseTest">
    <ignored/>
  </testcase> <!-- @BeforeTest initTestSuite -->
  <testcase name="@AfterTest afterTest" time="0.0" classname="testCases.BaseTest">
    <ignored/>
  </testcase> <!-- @AfterTest afterTest -->
</testsuite> <!-- Normal -->
