<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="2" total="4" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite1" duration-ms="47883" started-at="2019-12-09T19:50:17Z" finished-at="2019-12-09T19:51:04Z">
    <groups>
    </groups>
    <test name="Normal" duration-ms="47883" started-at="2019-12-09T19:50:17Z" finished-at="2019-12-09T19:51:04Z">
      <class name="testCases.LoginTestCases">
        <test-method status="PASS" signature="initTestSuite()[pri:0, instance:testCases.LoginTestCases@6293abcc]" name="initTestSuite" is-config="true" duration-ms="466" started-at="2019-12-09T19:50:17Z" finished-at="2019-12-09T19:50:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initTestSuite -->
        <test-method status="PASS" signature="initializeTestCase(java.lang.String)[pri:0, instance:testCases.LoginTestCases@6293abcc]" name="initializeTestCase" is-config="true" duration-ms="17233" started-at="2019-12-09T19:50:17Z" finished-at="2019-12-09T19:50:34Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[CHROME]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializeTestCase -->
        <test-method status="FAIL" signature="loginWithInvalidCredentials()[pri:0, instance:testCases.LoginTestCases@6293abcc]" name="loginWithInvalidCredentials" duration-ms="4565" started-at="2019-12-09T19:50:34Z" finished-at="2019-12-09T19:50:39Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login failed expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login failed expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertFalse(Assert.java:65)
at com.cloud.pageActions.LoginPage.loginInApp(LoginPage.java:46)
at testCases.LoginTestCases.loginWithInvalidCredentials(LoginTestCases.java:21)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithInvalidCredentials -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:testCases.LoginTestCases@6293abcc]" name="afterSuite" is-config="true" duration-ms="121" started-at="2019-12-09T19:50:39Z" finished-at="2019-12-09T19:50:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:testCases.LoginTestCases@6293abcc]" name="afterTest" is-config="true" duration-ms="296" started-at="2019-12-09T19:51:04Z" finished-at="2019-12-09T19:51:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- testCases.LoginTestCases -->
      <class name="testCases.TripsTesting">
        <test-method status="PASS" signature="initializeTestCase(java.lang.String)[pri:0, instance:testCases.TripsTesting@7995092a]" name="initializeTestCase" is-config="true" duration-ms="14376" started-at="2019-12-09T19:50:40Z" finished-at="2019-12-09T19:50:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[CHROME]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializeTestCase -->
        <test-method status="PASS" signature="validateShortestDurationInDeutscheBahn()[pri:0, instance:testCases.TripsTesting@7995092a]" name="validateShortestDurationInDeutscheBahn" duration-ms="10084" started-at="2019-12-09T19:50:54Z" finished-at="2019-12-09T19:51:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateShortestDurationInDeutscheBahn -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:testCases.TripsTesting@7995092a]" name="afterSuite" is-config="true" duration-ms="132" started-at="2019-12-09T19:51:04Z" finished-at="2019-12-09T19:51:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- testCases.TripsTesting -->
    </test> <!-- Normal -->
  </suite> <!-- Suite1 -->
</testng-results>
